/* PROGRAMMER: RUMAISA FATIMA 26K-0018
PROGRAM: Hotel Booking System
PART B QUESTION 1*/
#include <stdio.h>
int main() 
{
      
    int n=1; // loop counter
    int nguests,nights,rate=0; //nguests is number of guests, nights are the number of nights the guest is staying, rate is the cost of room according to the room type
    float totalp,revenue=0; //totalp is the total cost or bill of each customer, revenue is the total total revenue generated by each customer,
    char season, roomtyp; //season is the type of seasom, and roomtyp is the type of room
    printf("input the number of guests: ");
    scanf("%d",&nguests);
    while (n<=nguests)
    {
        //taking inputs from user 
        printf("input the details of guest %d:\n",n);
         printf("input the number of nights: ");
         scanf("%d",&nights);
         getchar();
         printf("input season (p for peak and o for off peak): ");
         scanf("%c",&season);
         getchar();
         printf("input room type (s for standard d for deluxe and u for suite): ");
         scanf("%c",&roomtyp);
         // selecting the rate according to season and room type
         if(season=='p')
         {
            if(roomtyp=='s')
            {
                rate=5000;
            }
            else if(roomtyp=='d')
            {
                rate=8000;
            }
            else if(roomtyp=='u')
            {
                rate=12000;
            }

         }
         else if(season=='o')
         {
            if(roomtyp=='s')
            {
                rate=3000;
            }
            else if(roomtyp=='d')
            {
                rate=5000;
            }
            else if(roomtyp=='u')
            {
                rate=8000;
            }

         }
         totalp=rate*nights; // calculating the total bill of each guest
         if(nights>7)
         {
            totalp=totalp-(totalp*0.15);// giving discount if number of nnights are greater than 7

         }

         printf("the total cost of guest %d is %.2f\n",n,totalp); // printing the total bil of each guest
        revenue=revenue+totalp;// calculating the revenue
        totalp=0;
         n++;
    }
    printf("total revenue is: %.2f",revenue);// printing the revenue
    
return 0;
}